language: java
jdk:
  - oraclejdk8
sudo: false
env:
  matrix:
    - PROFILE=glassfish-embedded
    - PROFILE=openejb-embedded
    - PROFILE=tomee-embedded
    - PROFILE=weld-se-embedded
    - PROFILE=wildfly-managed

script: "mvn clean test -P ${SLF4J_VERSION}"